name: Sync to Personal Repo

on:
  push:
    branches:
      - dev # or your default branch name

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Push to Personal Repository
      env:
        PERSONAL_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
        PERSONAL_REPO: seokjin909/WillYou-frontEnd
      run: |
        git remote add personal https://${PERSONAL_TOKEN}@github.com/${PERSONAL_REPO}.git
        git push personal HEAD:main
